baseurl = "https://hotice.netlify.com/"
languageCode = "zh-CN"
title = "HotIce"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = "HotIce"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
[[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "归档"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 4
# [[menu.main]]
#    name = "Subscribe"
#    url = "/index.xml"

[params]
    # description = "A Hugo theme ported from the static site generator Ivy."
    footer = "&copy; [Bing Liu](https://hotice.netlify.com) 2019 | [Github](https://github.com/qiaoin)"

  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "python", "julia",
                     "yaml", "tex", "markdown", "toml",
                     "postgres", "postgresql", "sql",
                     "bash", "shell",
                     "cmake", "c", "makefile"]
  highlightjsTheme = "github"
